version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearchs/config/elasticsearch.yml
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTIC_PASSWORD=root123
      - discovery.type=single-node
      - network.publish_host=_eth0_
  logstash:
    image: logstash:7.9.3
    ports:
      - 5044:5004
      - 5000:5000
      - 9600:9600
    volumes:
      - /data/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /data/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
  kibana:
    image: kibana:7.9.3
    ports:
      - 5601:5601
    volumes:
      - /data/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      